---
- name: Add ownCloud repo key
  apt_key:
    url='https://download.owncloud.org/download/repositories/stable/{{ ansible_distribution }}_8.0/Release.key'
    state=present

- name: Add ownCloud repo
  apt_repository:
    repo='deb http://download.owncloud.org/download/repositories/stable/{{ ansible_distribution }}_8.0/ /'
    state=present
    update_cache=yes

- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
     - php-zip
     - php-pgsql
     - php-xml
     - php-gd
     - php-curl
     - php-smb
     - php-smbclient
     - smbclient
  notify:
    - nginx restart

- name: Install ownCloud
  apt: name=owncloud state=present force=yes
  notify:
    - nginx restart

- name: Create ownCloud mysql database
  mysql_db:
    name: "{{ owncloud_database_db }}"
    encoding: "UTF-8"
    state: present

- name: Create ownCloud mysql database user
  mysql_user:
    name: "{{ owncloud_database_username }}"
    db: "{{ owncloud_database_db }}"
    password: "{{ owncloud_database_password }}"
    priv: ALL
    state: present
