---
- name: Add ownCloud repo key
  apt_key:
    url='https://download.owncloud.org/download/repositories/stable/{{ ansible_distribution }}_8.0/Release.key'
    state=present

- name: Add ownCloud repo
  apt_repository:
    repo='deb http://download.owncloud.org/download/repositories/stable/{{ ansible_distribution }}_8.0/ /'
    state=present
    update_cache=yes

- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
     - php-zip
     - php-xml
     - php-gd
     - php-ctype
     - php-curl
     - php-dom
     - php-simplexml
     - php-xmlwriter
     - php-json
     - php-posix
     - php-iconv
     - php-pdo-mysql
  notify:
    - nginx restart

- name: Install ownCloud
  apt: name=owncloud state=present force=yes
  notify:
    - nginx restart

- name: databases > Install python-mysqldb package
  apt:
    name: python-mysqldb
    state: present

- name: Create ownCloud mysql database
  mysql_db:
    name: "{{ owncloud_database_db }}"
    encoding: "utf8"
    login_password: "{{ owncloud_database_root_password }}"
    state: present

- name: Create ownCloud mysql database user
  mysql_user:
    name: "{{ owncloud_database_username }}"
    password: "{{ owncloud_database_password }}"
    login_password: "{{ owncloud_database_root_password }}"
    priv: "{{ owncloud_database_db }}.*:ALL"
    state: present
